<?php
$data = array (
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '水果/干果',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '5',
    'sort_order' => '1',
    'has_children' => '12',
    'goods_num' => '1',
    'level' => 0,
    'id' => '1',
    'name' => '水果/干果',
  ),
  28 => 
  array (
    'cat_id' => '28',
    'cat_name' => '核桃',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '28',
    'name' => '核桃',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => '双桂圆龙眼',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '5',
    'name' => '双桂圆龙眼',
  ),
  25 => 
  array (
    'cat_id' => '25',
    'cat_name' => '其它类水果',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '25',
    'name' => '其它类水果',
  ),
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => 'CD草莓',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '2',
    'name' => 'CD草莓',
  ),
  22 => 
  array (
    'cat_id' => '22',
    'cat_name' => '芭蕉',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '22',
    'name' => '芭蕉',
  ),
  29 => 
  array (
    'cat_id' => '29',
    'cat_name' => '瓜子',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '29',
    'name' => '瓜子',
  ),
  26 => 
  array (
    'cat_id' => '26',
    'cat_name' => '杏仁',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '26',
    'name' => '杏仁',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => '樱桃',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '3',
    'name' => '樱桃',
  ),
  23 => 
  array (
    'cat_id' => '23',
    'cat_name' => '奇异果',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '23',
    'name' => '奇异果',
  ),
  27 => 
  array (
    'cat_id' => '27',
    'cat_name' => '榛子',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '27',
    'name' => '榛子',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => '枣',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '4',
    'name' => '枣',
  ),
  24 => 
  array (
    'cat_id' => '24',
    'cat_name' => '猕猴桃',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '24',
    'name' => '猕猴桃',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '风味名吃',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '12',
    'goods_num' => 0,
    'level' => 0,
    'id' => '6',
    'name' => '风味名吃',
  ),
  37 => 
  array (
    'cat_id' => '37',
    'cat_name' => '湖北风味',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '37',
    'name' => '湖北风味',
  ),
  34 => 
  array (
    'cat_id' => '34',
    'cat_name' => '切糕',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '34',
    'name' => '切糕',
  ),
  31 => 
  array (
    'cat_id' => '31',
    'cat_name' => '罐头',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '31',
    'name' => '罐头',
  ),
  8 => 
  array (
    'cat_id' => '8',
    'cat_name' => '豆腐豆皮',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '8',
    'name' => '豆腐豆皮',
  ),
  35 => 
  array (
    'cat_id' => '35',
    'cat_name' => '湖南风味',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '35',
    'name' => '湖南风味',
  ),
  32 => 
  array (
    'cat_id' => '32',
    'cat_name' => '其它风味名',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '32',
    'name' => '其它风味名',
  ),
  9 => 
  array (
    'cat_id' => '9',
    'cat_name' => '烧鸡/烤鸭',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '9',
    'name' => '烧鸡/烤鸭',
  ),
  36 => 
  array (
    'cat_id' => '36',
    'cat_name' => '广西风味',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '36',
    'name' => '广西风味',
  ),
  33 => 
  array (
    'cat_id' => '33',
    'cat_name' => '鱼宴',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '33',
    'name' => '鱼宴',
  ),
  11 => 
  array (
    'cat_id' => '11',
    'cat_name' => '锅贴/馅饼/盒',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '11',
    'name' => '锅贴/馅饼/盒',
  ),
  30 => 
  array (
    'cat_id' => '30',
    'cat_name' => '腊肉/腊肠/灌',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '30',
    'name' => '腊肉/腊肠/灌',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => '风味糕点/麻',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '7',
    'name' => '风味糕点/麻',
  ),
  12 => 
  array (
    'cat_id' => '12',
    'cat_name' => '罐头火腿/腌泡菜/烤干',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => '8',
    'level' => 0,
    'id' => '12',
    'name' => '罐头火腿/腌泡菜/烤干',
  ),
  16 => 
  array (
    'cat_id' => '16',
    'cat_name' => '方便食品类',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => '8',
    'level' => 0,
    'id' => '16',
    'name' => '方便食品类',
  ),
  17 => 
  array (
    'cat_id' => '17',
    'cat_name' => '饮料/冲调品/蜂蜜类',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => '8',
    'level' => 0,
    'id' => '17',
    'name' => '饮料/冲调品/蜂蜜类',
  ),
  18 => 
  array (
    'cat_id' => '18',
    'cat_name' => '糖果/果冻/果脯类',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '18',
    'name' => '糖果/果冻/果脯类',
  ),
  19 => 
  array (
    'cat_id' => '19',
    'cat_name' => '花卉/草木类',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '19',
    'name' => '花卉/草木类',
  ),
  20 => 
  array (
    'cat_id' => '20',
    'cat_name' => '滋补品/药材及制品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '20',
    'name' => '滋补品/药材及制品',
  ),
  21 => 
  array (
    'cat_id' => '21',
    'cat_name' => '干鲜水产品及制品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '9',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '21',
    'name' => '干鲜水产品及制品',
  ),
);
?>